<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
        table,
        td,
        th {
            border: 1px solid bredlarck;
            border-collapse: collapse;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .header {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .center {
            width: 33.33%;
            float: left;
        }

        .center1 {
            width: 50%;
            float: left;
        }

        div {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

    </style>
</head>

<body>


<div class="header">
    <div class="center">
        <img src="{{ $draftPurchaseOrders[0]->buyer_business->business_photo_url }}" alt="{{ $draftPurchaseOrders[0]->buyer_business->business_name }}" />
        <h5 style="text-align: center; margin:0px;">{{ $draftPurchaseOrders[0]->buyer_business->business_name }}</h5>
    </div>

    <div class="center">
        <h3 style="text-align: center; margin:0px;">Purchase Order</h3>
    </div>

    <div class="center">
        <img src="{{ $draftPurchaseOrders[0]->supplier_business->business_photo_url }}" alt="{{ $draftPurchaseOrders[0]->supplier_business->business_name }}" />
        <h5 style="text-align: center; margin:0px;">{{ $draftPurchaseOrders[0]->supplier_business->business_name }}</h5>
    </div>


    <br>
    <br>
    <br>
    <br>
    <div class="center">
        <strong>Generated By: </strong><br>
        <p>{{ $draftPurchaseOrders[0]->buyer_business->business_name }}</p><br>
        <strong>ID: </strong> {{ $draftPurchaseOrders[0]->buyer_business->user_id }}<br>
        <strong>City: </strong>{{ $draftPurchaseOrders[0]->buyer_business->city }}<br>
    </div>

    <div class="center">
        <strong>Purchased From: </strong><br>
        <p>{{ $draftPurchaseOrders[0]->supplier_business->business_name }}</p><br>
        <strong>ID: </strong>{{ $draftPurchaseOrders[0]->supplier_business->user_id }}<br>
        <strong>City: </strong>{{ $draftPurchaseOrders[0]->supplier_business->city }}<br>
    </div>

    <div class="center">
        <h3 class="text-2xl text-center"><strong>P.O.</strong></h3>
        <strong>P.O. #: </strong>P.O. -{{ $draftPurchaseOrders[0]->id }}<br>
{{--        <strong>Category Code: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ $draftPurchaseOrders[0]->item_code }}<br>--}}
        <strong>Category Name: </strong>{{ $draftPurchaseOrders[0]->item_name }}<br>
        <strong>Date: </strong>{{ $draftPurchaseOrders[0]->created_at }}<br>
        <strong>Requisition #: </strong>RFQ-{{ $draftPurchaseOrders[0]->rfq_no }}<br>
        <strong>Quotation #: </strong>Q-{{ $draftPurchaseOrders[0]->qoute_no }}<br>
        <strong>Payment Terms: </strong>{{ $draftPurchaseOrders[0]->payment_term }}<br>
        <strong>VAT %: </strong>{{ number_format($draftPurchaseOrders[0]->vat, 2) }}<br>
        <strong>Shipping Fees: </strong>{{ number_format($draftPurchaseOrders[0]->shipment_cost, 2) }}<br>
        <strong>Total: </strong>{{ number_format($draftPurchaseOrders[0]->total_cost, 2) }}<br>
    </div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<table style="margin-top: 4%;width: 100%">
    <thead>
    <tr>
        <th scope="col" style="text-align: center">
            #
        </th>
        <th scope="col" style="text-align: center">
            Brand
        </th>
        <th scope="col" style="text-align: center">
            UOM
        </th>
        <th scope="col" style="text-align: center">
            Remarks
        </th>
        <th scope="col" style="text-align: center">
            Unit Price
        </th>
        <th scope="col" style="text-align: center">
            Quantity
        </th>
        <th scope="col" style="text-align: center">
            Amount
        </th>
    </tr>
    </thead>
    @foreach($draftPurchaseOrders as $draftPurchaseOrder)
        <tbody class="bg-white divide-y divide-black border-1 border-black">
        <tr>
            <td style="text-align: center">
                {{$loop->iteration}}
            </td>
            <td style="text-align: center">
                {{ $draftPurchaseOrder->brand }}
            </td>
            <td style="text-align: center">
                {{ $draftPurchaseOrder->uom }}
            </td>
            <td style="text-align: center">
                @if(isset($draftPurchaseOrder->remarks)){{ strip_tags($draftPurchaseOrder->remarks) }} @else N/A @endif
            </td>
            <td style="text-align: center">
                {{ $draftPurchaseOrder->unit_price }}
            </td>

            <td style="text-align: center">
                {{ $draftPurchaseOrder->quantity }}
            </td>
            <td style="text-align: center">
                {{ number_format($draftPurchaseOrder->sub_total, 2) }}
            </td>
        </tr>
        </tbody>
    @endforeach
</table>


<br>
<br>


<div class="flex flex-wrap overflow-hidden  p-4 mt-4">
    <div class="w-full overflow-hidden lg:w-1/2 xl:w-1/2">
        <strong>Delivery Information: </strong><br>
        <strong>City: </strong> {{ $draftPurchaseOrders[0]->buyer_business->city }}<br>
        @php $warehouse = \App\Models\BusinessWarehouse::where('id', $draftPurchaseOrders[0]->warehouse_id)->first(); @endphp
        <strong>Warehouse: </strong>{{$warehouse->address}}<br>

    </div>
</div>
<br>
<br>
<br>

<div class="flex justify-center">
    {{--        <div><img src="{{ url('logo-full.png') }}" alt="EMDAD CHAIN LOGO" class="block h-10 w-auto" /></div>--}}
</div>

<div class="flex justify-between px-2 py-2 mt-2 h-15">
    <div style="text-align: center; margin: auto;">
        <p style="text-align: center; ">Thank you for using Emdad platform as your business partner </p>
    <!--<img src="{{ url(Storage::url('logo-full.png')) }}" />-->
        @php $img = asset('logo-full.png'); @endphp

        <img src="@php echo $img @endphp" width="100" >

    </div>

</div>

</body>
