@if (auth()->user()->rtl == 0)
    <x-app-layout>
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-2 lg:2x-8">
                <div class="bg-white overflow-hidden shadow-xl ">
                    <div class="mt-5" style=" margin-left: 30px; margin-bottom: 10px ">
                        {{--<a href="{{ route('generatePDF', $draftPurchaseOrder) }}"
                           class="inline-flex items-center justify-center px-4 py-2 bg-blue-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-600 transition ease-in-out duration-150">
                            Create PDF
                        </a>--}}
                    </div>
                    <div class="px-4 py-5 sm:p-6 bg-white shadow ">
                        <div class="flex flex-wrap overflow-hidden bg-gray-100 p-4">
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <img class="h-20 w-20 rounded-full object-cover" src="{{ Storage::url($draftPurchaseOrder->buyer_business->business_photo_url) }}" alt="{{ $draftPurchaseOrder->buyer_business->business_name }}"/>
                                <h1 class="text-center text-2xl">{{ $draftPurchaseOrder->buyer_business->business_name }}</h1>
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <h1 class="text-center text-3xl">{{__('portal.Draft Purchase Order')}}</h1>
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <img class="h-20 w-20 rounded-full object-cover" src="{{ Storage::url($draftPurchaseOrder->supplier_business->business_photo_url) }}" alt="{{ $draftPurchaseOrder->supplier_business->business_name }}"/>
                                <h1 class="text-center text-2xl">{{ $draftPurchaseOrder->supplier_business->business_name }}</h1>
                            </div>
                        </div>

                        <div class="flex flex-wrap overflow-hidden bg-white p-4">
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <strong class="text-xl">{{__('portal.Generated By')}}: </strong><br>
                                <p class="text-xl">{{ $draftPurchaseOrder->buyer_business->business_name }}</p><br>

                                <strong class="text-xl">{{__('portal.City')}}: </strong><span class="text-xl">{{ $draftPurchaseOrder->buyer_business->city }}</span> <br>
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <strong class="text-xl">{{__('portal.Purchased From')}}: </strong><br>
                                <p class="text-xl">{{ $draftPurchaseOrder->supplier_business->business_name }}</p><br>

                                <strong class="text-xl">{{__('portal.City')}}: </strong><span class="text-xl">{{ $draftPurchaseOrder->supplier_business->city }}</span> <br>
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3 ">
                                {{--<h3 class="text-2xl" style="padding-left: 55px"><strong>{{__('portal.Draft P.O.')}}</strong></h3>--}}
                                <strong>{{__('portal.D.P.O.')}} #: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{__('portal.D.P.O.')}} -{{ $draftPurchaseOrder->id }}<br>
                                <strong>{{__('portal.Date')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ $draftPurchaseOrder->created_at }}<br>
                                <strong>{{__('portal.Category Name')}}: &nbsp;&nbsp;&nbsp;</strong>
                                @php
                                    $record = \App\Models\Category::where('id',$draftPurchaseOrder->item_code)->first();
                                    $parent= \App\Models\Category::where('id',$record->parent_id)->first();
                                @endphp
                                    {{ $record->name }} @if(isset($parent)) , {{ $parent->name }} @endif
{{--                                    {{ $draftPurchaseOrder->item_name }}--}}
                                <br>
                                <strong>{{__('portal.Requisition')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{__('portal.RFQ')}}-{{ $draftPurchaseOrder->rfq_no }}<br>
                                <strong>{{__('portal.Quote')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{__('portal.Q')}}-{{ $draftPurchaseOrder->qoute_no }}<br>
                                <strong>{{__('portal.Payment Terms')}}: &nbsp;&nbsp;&nbsp;</strong>
                                    @if($draftPurchaseOrder->payment_term == 'Cash') {{__('portal.Cash')}}
                                    @elseif($draftPurchaseOrder->payment_term == 'Credit') {{__('portal.Credit')}}
                                    @elseif($draftPurchaseOrder->payment_term == 'Credit30days') {{__('portal.Credit (30 Days)')}}
                                    @elseif($draftPurchaseOrder->payment_term == 'Credit60days') {{__('portal.Credit (60 Days)')}}
                                    @elseif($draftPurchaseOrder->payment_term == 'Credit90days') {{__('portal.Credit (90 Days)')}}
                                    @elseif($draftPurchaseOrder->payment_term == 'Credit120days') {{__('portal.Credit (120 Days)')}}
                                    @endif
{{--                                    {{ $draftPurchaseOrder->payment_term }}--}}
                                <br>
                            </div>
                        </div>
                        <table class="min-w-full divide-y divide-black ">
                            <thead>
                                <tr>
                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        #
                                    </th>
                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.Quantity')}}
                                    </th>
                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.Unit Price')}}
                                    </th>
                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.UOM')}}
                                    </th>

                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.Brand')}}
                                    </th>

                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.Remarks')}}
                                    </th>

                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.Amount')}}
                                    </th>
                                </tr>
                            </thead>
                            <tbody class="bg-white divide-y divide-black border-1 border-black">
                            <tr>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    1
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    {{ $draftPurchaseOrder->quantity }}
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    {{ $draftPurchaseOrder->unit_price }} {{__('portal.SAR')}}
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    {{ $draftPurchaseOrder->uom }}
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    {{ $draftPurchaseOrder->brand }}
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    @if(isset($draftPurchaseOrder->remarks)) {{ strip_tags($draftPurchaseOrder->remarks) }} @else {{__('portal.N/A')}} @endif
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    {{ number_format($draftPurchaseOrder->sub_total, 2) }} {{__('portal.SAR')}}
                                </td>
                            </tr>
                            </tbody>
                        </table>

                        <div class="flex flex-wrap overflow-hidden bg-white p-4">
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <strong>{{__('portal.Sub-total')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ number_format($draftPurchaseOrder->sub_total, 2) }} {{__('portal.SAR')}}<br>
                                <strong>{{__('portal.VAT')}} %: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ number_format($draftPurchaseOrder->sub_total * ($draftPurchaseOrder->vat/100), 2) }} {{__('portal.SAR')}}<br>
                                <strong>{{__('portal.Shipment cost')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ number_format($draftPurchaseOrder->shipment_cost, 2) }} {{__('portal.SAR')}}<br>
                                <hr>
                                <strong>{{__('portal.Total')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ number_format(($draftPurchaseOrder->sub_total + ($draftPurchaseOrder->sub_total * ($draftPurchaseOrder->vat/100) + $draftPurchaseOrder->shipment_cost)),2) }}  {{__('portal.SAR')}}<br>
                                <hr>
                            </div>
                        </div>

                        <div class="flex flex-wrap overflow-hidden  p-4 mt-4">
                            <div class="w-full overflow-hidden lg:w-1/2 xl:w-2/3">
                                <strong>{{__('portal.Mobile Number for OTP')}}: </strong> {{ $draftPurchaseOrder->otp_mobile_number }} <br>
                                <strong>{{__('portal.Delivery Address')}}: </strong> {{ strip_tags($draftPurchaseOrder->delivery_address) }} <br>
                                <strong class="text-red-900">{{__('portal.Note')}}: </strong> <span class="text-red-700">
                                {{__('portal.We acknowledge that')}} {{$draftPurchaseOrder->buyer_business->business_name }}
                                {{__('portal.agrees to deal with')}} {{$draftPurchaseOrder->supplier_business->business_name}}. <br>
                                {{__('portal.Emdad has no responsibility with the kind of delivery and the source of finance for this delivery.')}}</span> <br>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" name="note" id="acknowledge" required>
                                    <label class="form-check-label" for="flexCheckDefault">
                                        {{__('portal.Please read the note and check if you agree to proceed')}}
                                    </label>
                                </div>
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/2 xl:w-1/2">
                                {{-- <strong>Delivery Information</strong><br>
                                @php $warehouseName =  \App\Models\BusinessWarehouse::where('id', $draftPurchaseOrder->warehouse)->first(); @endphp
                                <strong>Warehouse: @if(isset($warehouseName)){{$warehouseName->name}} @endif</strong><br> --}}

                            </div>
                        </div>


                        <div class="flex justify-center">
                            <div><img src="{{ url('logo-full.png') }}" alt="EMDAD CHAIN LOGO" class="block" style="height: 104px"/></div>
                        </div>


                        <div class="flex justify-between mt-4 mb-4">


                            @if ($draftPurchaseOrder->status == 'approved')
                                <img src="" alt="">
                                <span class="px-3 py-3 bg-green-800 text-white rounded">{{__('portal.Approve')}}</span>
                            @elseif ($draftPurchaseOrder->status == 'cancel')
                                <span class="px-3 py-3 bg-red-800 text-white rounded">{{__('portal.Cancel DPO')}}</span>
                            @elseif ($draftPurchaseOrder->status == 'rejectToEdit')
                                <span class="px-3 py-3 bg-red-600 text-white rounded uppercase">{{__('portal.Rejected for Edit')}}</span>
                            @else
                                @if(auth()->user()->can('Buyer Quotation Response') || auth()->user()->hasRole('CEO'))
                                    @if($draftPurchaseOrder->payment_term == 'Cash')
                                        <form method="post" action="{{route('cashDpo.approved', $draftPurchaseOrder->id)}}" class="confirm">
                                            @csrf
                                            <input type="hidden" value="{{ $draftPurchaseOrder->rfq_no }}" name="rfq_no">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->rfq_item_no }}" name="rfq_item_no">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->qoute_no }}" name="qoute_no">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->id }}" name="draft_purchase_order_id">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->user_id }}" name="buyer_user_id">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->business_id }}" name="buyer_business_id">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->supplier_user_id }}" name="supplier_user_id">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->supplier_business_id }}" name="supplier_business_id">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->payment_term }}" name="payment_method">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->shipment_cost }}" name="shipment_cost">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->vat }}" name="vat">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->total_cost }}" name="total_cost">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->ship_to_address }}" name="ship_to_address">

                                            <button type="submit" class="inline-flex items-center justify-center px-4 py-2 bg-green-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-green-500 focus:outline-none focus:border-red-700 focus:shadow-outline-green active:bg-green-600 transition ease-in-out duration-150">Approve DPO</button>
                                        </form>
                                    @else
                                        <form method="POST" action="{{route('dpo.approved', $draftPurchaseOrder->id) }}" class="confirm">
                                            @csrf
                                            <button type="submit" class="inline-flex items-center justify-center px-4 py-2 bg-green-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-green-500 focus:outline-none focus:border-red-700 focus:shadow-outline-green active:bg-green-600 transition ease-in-out duration-150">
                                                {{__('portal.Approve DPO')}}
                                            </button>
                                        </form>
                                    @endif
                                        <a href="{{ route('dpo.cancel', $draftPurchaseOrder->id) }}" onclick="cancel()"
                                           class="inline-flex items-center justify-center px-4 py-2 bg-red-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-600 transition ease-in-out duration-150">
                                            {{__('portal.Cancel DPO')}}
                                        </a>
                                @endif
                                {{-- <a href="{{ route('dpo.rejected', $draftPurchaseOrder->id) }}" class="inline-flex  mx-4  items-center px-4 py-2 bg-red-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-700 active:bg-red-900 focus:outline-none focus:border-red-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">Reject to Edit</a> --}}
                            @endif


                        </div>

                        <div class="flex justify-between px-2 py-2 mt-2 h-15">
                            <div></div>
                            <div class="mt-3">{{__('portal.Thanks for your Business')}}</div>
                            <div><img src="{{ url('logo-full.png') }}" alt="EMDAD CHAIN LOGO" class="block" style="height: 60px"/></div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </x-app-layout>

    <script>

        $('.confirm').on('click', function (e) {
            if (!$("#acknowledge").is(":checked")) {
                // do something if the checkbox is NOT checked
                alert('Please read the note and check if you agree to proceed')
                event.preventDefault();
            }
            else if ($("#acknowledge").is(":checked")) {
                if(!confirm('Are you sure?')){
                    e.preventDefault();
                }
            }
        });

        function cancel() {
            if(!confirm('Are you sure?')){
                event.preventDefault();
            }
        }
    </script>
@else
    <x-app-layout>
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-2 lg:2x-8">
                <div class="bg-white overflow-hidden shadow-xl ">
                    <div class="mt-5" style=" margin-left: 30px; margin-bottom: 10px ">
                        {{--<a href="{{ route('generatePDF', $draftPurchaseOrder) }}"
                           class="inline-flex items-center justify-center px-4 py-2 bg-blue-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-600 transition ease-in-out duration-150">
                            Create PDF
                        </a>--}}
                    </div>
                    <div class="px-4 py-5 sm:p-6 bg-white shadow ">
                        <div class="flex flex-wrap overflow-hidden bg-gray-100 p-4">
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <img class="h-20 w-20 rounded-full object-cover" src="{{ Storage::url($draftPurchaseOrder->buyer_business->business_photo_url) }}" alt="{{ $draftPurchaseOrder->buyer_business->business_name }}"/>
                                <h1 class="text-center text-2xl">{{ $draftPurchaseOrder->buyer_business->business_name }}</h1>
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <h1 class="text-center text-3xl">{{__('portal.Draft Purchase Order')}}</h1>
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <img class="h-20 w-20 rounded-full object-cover" src="{{ Storage::url($draftPurchaseOrder->supplier_business->business_photo_url) }}" alt="{{ $draftPurchaseOrder->supplier_business->business_name }}"/>
                                <h1 class="text-center text-2xl">{{ $draftPurchaseOrder->supplier_business->business_name }}</h1>
                            </div>
                        </div>

                        <div class="flex flex-wrap overflow-hidden bg-white p-4">
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <strong class="text-xl">{{__('portal.Generated By')}}: </strong><br>
                                <p class="text-xl">{{ $draftPurchaseOrder->buyer_business->business_name }}</p><br>

                                <strong class="text-xl">{{__('portal.City')}}: </strong><span class="text-xl">{{ $draftPurchaseOrder->buyer_business->city }}</span> <br>
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <strong class="text-xl">{{__('portal.Purchased From')}}: </strong><br>
                                <p class="text-xl">{{ $draftPurchaseOrder->supplier_business->business_name }}</p><br>

                                <strong class="text-xl">{{__('portal.City')}}: </strong> <span class="text-xl">{{ $draftPurchaseOrder->supplier_business->city }}</span> <br>
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3 ">
                                {{--<h3 class="text-2xl" style="padding-right: 55px"><strong>{{__('portal.Draft P.O.')}}</strong></h3>--}}
                                <strong>{{__('portal.D.P.O.')}} #: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{__('portal.D.P.O.')}}-{{ $draftPurchaseOrder->id }}<br>
                                <strong>{{__('portal.Date')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ $draftPurchaseOrder->created_at }}<br>
                                <strong>{{__('portal.Category Name')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>
                                @php
                                    $record = \App\Models\Category::where('id',$draftPurchaseOrder->item_code)->first();
                                    $parent= \App\Models\Category::where('id',$record->parent_id)->first();
                                @endphp
                                {{ $record->name_ar }} @if(isset($parent)) , {{ $parent->name_ar }} @endif
                                {{--                                    {{ $draftPurchaseOrder->item_name }}--}}
                                <br>
                                <strong>{{__('portal.Requisition')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{__('portal.RFQ')}}-{{ $draftPurchaseOrder->rfq_no }}<br>
                                <strong>{{__('portal.Quote')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{__('portal.Q')}}-{{ $draftPurchaseOrder->qoute_no }}<br>
                                <strong>{{__('portal.Payment Terms')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>
                                    @if($draftPurchaseOrder->payment_term == 'Cash') {{__('portal.Cash')}}
                                    @elseif($draftPurchaseOrder->payment_term == 'Credit') {{__('portal.Credit')}}
                                    @elseif($draftPurchaseOrder->payment_term == 'Credit30days') {{__('portal.Credit (30 Days)')}}
                                    @elseif($draftPurchaseOrder->payment_term == 'Credit60days') {{__('portal.Credit (60 Days)')}}
                                    @elseif($draftPurchaseOrder->payment_term == 'Credit90days') {{__('portal.Credit (90 Days)')}}
                                    @elseif($draftPurchaseOrder->payment_term == 'Credit120days') {{__('portal.Credit (120 Days)')}}
                                    @endif
{{--                                    {{ $draftPurchaseOrder->payment_term }}--}}
                                <br>
                            </div>
                        </div>
                        <table class="min-w-full divide-y divide-black ">
                            <thead>
                                <tr>
                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        #
                                    </th>
                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.Quantity')}}
                                    </th>
                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.Unit Price')}}
                                    </th>
                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.UOM')}}
                                    </th>

                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.Brand')}}
                                    </th>

                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.Remarks')}}
                                    </th>

                                    <th scope="col" class="px-2 py-2 border border-black text-center text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                                        {{__('portal.Amount')}}
                                    </th>
                                </tr>
                            </thead>
                            <tbody class="bg-white divide-y divide-black border-1 border-black">
                            <tr>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    1
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    {{ $draftPurchaseOrder->quantity }}
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    {{ $draftPurchaseOrder->unit_price }} {{__('portal.SAR')}}
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    {{ $draftPurchaseOrder->uom }}
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    {{ $draftPurchaseOrder->brand }}
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    @if(isset($draftPurchaseOrder->remarks)) {{ strip_tags($draftPurchaseOrder->remarks) }} @else {{__('portal.N/A')}} @endif
                                </td>
                                <td class="px-2 py-2 whitespace-nowrap text-sm text-center text-black  border border-black">
                                    {{ number_format($draftPurchaseOrder->sub_total, 2) }} {{__('portal.SAR')}}
                                </td>
                            </tr>
                            </tbody>
                        </table>

                        <div class="flex flex-wrap overflow-hidden bg-white p-4">
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                                <strong>{{__('portal.Sub-total')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ number_format($draftPurchaseOrder->sub_total, 2) }} {{__('portal.SAR')}}<br>
                                <strong>{{__('portal.VAT')}} %: &nbsp;</strong>{{ number_format($draftPurchaseOrder->sub_total * ($draftPurchaseOrder->vat/100), 2) }} {{__('portal.SAR')}}<br>
                                <strong>{{__('portal.Shipment cost')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ number_format($draftPurchaseOrder->shipment_cost, 2) }} {{__('portal.SAR')}}<br>
                                <hr>
                                <strong>{{__('portal.Total')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ number_format(($draftPurchaseOrder->sub_total + ($draftPurchaseOrder->sub_total * ($draftPurchaseOrder->vat/100) + $draftPurchaseOrder->shipment_cost)),2) }}  {{__('portal.SAR')}}<br>
                                <hr>
                            </div>
                        </div>

                        <div class="flex flex-wrap overflow-hidden  p-4 mt-4">
                            <div class="w-full overflow-hidden lg:w-1/2 xl:w-2/3">
                                <strong>{{__('portal.Mobile Number for OTP')}}: </strong> {{ $draftPurchaseOrder->otp_mobile_number }} <br>
                                <strong>{{__('portal.Delivery Address')}}: </strong> {{ strip_tags($draftPurchaseOrder->delivery_address) }} <br>
                                <strong class="text-red-900">{{__('portal.Note')}}: </strong> <span class="text-red-700">
                                {{__('portal.We acknowledge that')}} {{$draftPurchaseOrder->buyer_business->business_name }}
                                    {{__('portal.agrees to deal with')}} {{$draftPurchaseOrder->supplier_business->business_name}}. <br>
                                {{__('portal.Emdad has no responsibility with the kind of delivery and the source of finance for this delivery.')}}</span> <br>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" name="note" id="acknowledge" required>
                                    <label class="form-check-label" for="flexCheckDefault">
                                        {{__('portal.Please read the note and check if you agree to proceed')}}
                                    </label>
                                </div>
                            </div>
                            <div class="w-full overflow-hidden lg:w-1/2 xl:w-1/2">
                                {{-- <strong>Delivery Information</strong><br>
                                @php $warehouseName =  \App\Models\BusinessWarehouse::where('id', $draftPurchaseOrder->warehouse)->first(); @endphp
                                <strong>Warehouse: @if(isset($warehouseName)){{$warehouseName->name}} @endif</strong><br> --}}

                            </div>
                        </div>


                        <div class="flex justify-center">
                            <div><img src="{{ url('logo-full.png') }}" alt="EMDAD CHAIN LOGO" class="block" style="height: 104px"/></div>
                        </div>


                        <div class="flex justify-between mt-4 mb-4">


                            @if ($draftPurchaseOrder->status == 'approved')
                                <img src="" alt="">
                                <span class="px-3 py-3 bg-green-800 text-white rounded">{{__('portal.Approve')}}</span>
                            @elseif ($draftPurchaseOrder->status == 'cancel')
                                <span class="px-3 py-3 bg-red-800 text-white rounded">{{__('portal.Cancel DPO')}}</span>
                            @elseif ($draftPurchaseOrder->status == 'rejectToEdit')
                                <span class="px-3 py-3 bg-red-600 text-white rounded uppercase">{{__('portal.Rejected for Edit')}}</span>
                            @else
                                @if(auth()->user()->can('Buyer Quotation Response') || auth()->user()->hasRole('CEO'))
                                    @if($draftPurchaseOrder->payment_term == 'Cash')
                                        <form method="post" action="{{route('cashDpo.approved', $draftPurchaseOrder->id)}}" class="confirm">
                                            @csrf
                                            <input type="hidden" value="{{ $draftPurchaseOrder->rfq_no }}" name="rfq_no">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->rfq_item_no }}" name="rfq_item_no">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->qoute_no }}" name="qoute_no">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->id }}" name="draft_purchase_order_id">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->user_id }}" name="buyer_user_id">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->business_id }}" name="buyer_business_id">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->supplier_user_id }}" name="supplier_user_id">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->supplier_business_id }}" name="supplier_business_id">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->payment_term }}" name="payment_method">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->shipment_cost }}" name="shipment_cost">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->vat }}" name="vat">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->total_cost }}" name="total_cost">
                                            <input type="hidden" value="{{ $draftPurchaseOrder->ship_to_address }}" name="ship_to_address">

                                            <button type="submit" class="inline-flex items-center justify-center px-4 py-2 bg-green-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-green-500 focus:outline-none focus:border-red-700 focus:shadow-outline-green active:bg-green-600 transition ease-in-out duration-150">Approve DPO</button>
                                        </form>
                                    @else
                                        <form method="POST" action="{{route('dpo.approved', $draftPurchaseOrder->id) }}" class="confirm">
                                            @csrf
                                            <button type="submit" class="inline-flex items-center justify-center px-4 py-2 bg-green-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-green-500 focus:outline-none focus:border-red-700 focus:shadow-outline-green active:bg-green-600 transition ease-in-out duration-150">
                                                {{__('portal.Approve DPO')}}
                                            </button>
                                        </form>
                                    @endif
                                    <a href="{{ route('dpo.cancel', $draftPurchaseOrder->id) }}" onclick="cancel()"
                                       class="inline-flex items-center justify-center px-4 py-2 bg-red-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-500 hover:text-white focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-600 transition ease-in-out duration-150">
                                        {{__('portal.Cancel DPO')}}
                                    </a>
                                @endif
                                {{-- <a href="{{ route('dpo.rejected', $draftPurchaseOrder->id) }}" class="inline-flex  mx-4  items-center px-4 py-2 bg-red-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-700 active:bg-red-900 focus:outline-none focus:border-red-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">Reject to Edit</a> --}}
                            @endif


                        </div>

                        <div class="flex justify-between px-2 py-2 mt-2 h-15">
                            <div></div>
                            <div class="mt-3">{{__('portal.Thanks for your Business')}}</div>
                            <div><img src="{{ url('logo-full.png') }}" alt="EMDAD CHAIN LOGO" class="block" style="height: 60px"/></div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </x-app-layout>

    <script>

        $('.confirm').on('click', function (e) {
            if (!$("#acknowledge").is(":checked")) {
                // do something if the checkbox is NOT checked
                alert('يرجى قراءة الملاحظة والتأكيد في حال الموافقة للمتابعة')
                event.preventDefault();
            }
            else if ($("#acknowledge").is(":checked")) {
                if(!confirm('هل أنت متأكد؟')){
                    e.preventDefault();
                }
            }
        });

        function cancel() {
            if(!confirm('هل أنت متأكد؟')){
                event.preventDefault();
            }
        }
    </script>
@endif
