<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        .page-break {
            page-break-after: always;
        }

        @font-face {
            font-family: "arabicFont";
            font-style: normal;
            font-weight: normal;
            src: url(http://127.0.0.1:8000/Presento/assets/arabicfont/arabic_regular.ttf) format('truetype');
        }

        * {
            font-family: "arabicFont";
        }

    </style>
</head>
<body>

<div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-2 lg:2x-8">
        <div class="bg-white overflow-hidden shadow-xl ">
            <div class="px-4 py-5 sm:p-6 bg-white shadow ">
                <div class="flex flex-wrap overflow-hidden bg-gray-300 p-4">
                    <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                        <img class="h-20 w-20 rounded-full object-cover" src="{{ $draftPurchaseOrder->buyer_business->business_photo_url }}" alt="{{ $draftPurchaseOrder->buyer_business->business_name }}" />
                        <h1 class="text-center text-2xl">{{ $draftPurchaseOrder->buyer_business->business_name }}</h1>
                    </div>
                    <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                        <h1 class="text-center text-3xl">{{__('portal.Purchase Order')}}</h1>
                    </div>
                    <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                        <img class="h-20 w-20 rounded-full object-cover" src="{{ $draftPurchaseOrder->supplier_business->business_photo_url }}" alt="{{ $draftPurchaseOrder->supplier_business->business_name }}" />
                        <h1 class="text-center text-2xl">{{ $draftPurchaseOrder->supplier_business->business_name }}</h1>
                    </div>
                </div>


                <div class="flex flex-wrap overflow-hidden bg-white p-4">
                    <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                        <strong class="text-xl">{{__('portal.Generated By')}}: </strong><br>
                        <p class="text-xl">{{ $draftPurchaseOrder->buyer_business->business_name }}</p><br>
                        <strong class="text-xl">{{__('portal.City')}}: </strong><span class="text-xl">{{ $draftPurchaseOrder->buyer_business->city }}</span><br>
                    </div>
                    <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                        <strong class="text-xl">{{__('portal.Purchased From')}}: </strong><br>
                        <p class="text-xl">{{ $draftPurchaseOrder->supplier_business->business_name }}</p><br>

                        <strong class="text-xl">{{__('portal.City')}}: </strong><span class="text-xl">{{ $draftPurchaseOrder->supplier_business->city }}</span><br>
                    </div>
                    <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3 ">
                        {{--<h3 class="text-2xl" style="padding-left: 55px;"><strong>{{__('portal.Purchase Order')}}</strong></h3>--}}
                        <strong>{{__('portal.P.O.')}} #: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{__('portal.P.O.')}} -{{ $draftPurchaseOrder->id }}<br>
                        <strong>{{__('portal.Date')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ $draftPurchaseOrder->created_at }}<br>
                        <strong>{{__('portal.Category Name')}}: &nbsp;&nbsp;&nbsp;&nbsp;</strong>
                        @php
                            $record = \App\Models\Category::where('id',$draftPurchaseOrder->item_code)->first();
                            $parent= \App\Models\Category::where('id',$record->parent_id)->first();
                        @endphp
                        {{ $record->name }} @if(isset($parent)) , {{ $parent->name }} @endif
                        <br>
                        <strong>{{__('portal.Requisition')}} #: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{__('portal.RFQ')}}-{{ $draftPurchaseOrder->rfq_no }}<br>
                        <strong>{{__('portal.Quote')}} #: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{__('portal.Q')}}-{{ $draftPurchaseOrder->qoute_no }}<br>
                        <strong>{{__('portal.Payment Terms')}}: &nbsp;&nbsp;&nbsp;&nbsp;</strong>
                        @if($draftPurchaseOrder->payment_term == 'Cash') {{__('portal.Cash')}}
                        @elseif($draftPurchaseOrder->payment_term == 'Credit') {{__('portal.Credit')}}
                        @elseif($draftPurchaseOrder->payment_term == 'Credit30days') {{__('portal.Credit (30 Days)')}}
                        @elseif($draftPurchaseOrder->payment_term == 'Credit60days') {{__('portal.Credit (60 Days)')}}
                        @elseif($draftPurchaseOrder->payment_term == 'Credit90days') {{__('portal.Credit (90 Days)')}}
                        @elseif($draftPurchaseOrder->payment_term == 'Credit120days') {{__('portal.Credit (120 Days)')}}
                        @endif
                        {{--                                    {{ $draftPurchaseOrder->payment_term }}--}}
                        <br>
                    </div>
                </div>
                <table class="min-w-full divide-y divide-black ">
                    <thead>
                    <tr>
                        <th scope="col" class="px-2 py-2 border border-black text-left text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                            #
                        </th>
                        {{--<th scope="col" class="px-2 py-2 border border-black text-left text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                            Category Number
                        </th>--}}
                        <th scope="col" class="px-2 py-2 border border-black text-left text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                            {{__('portal.Quantity')}}
                        </th>
                        <th scope="col" class="px-2 py-2 border border-black text-left text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                            {{__('portal.Unit Price')}}
                        </th>
                        <th scope="col" class="px-2 py-2 border border-black text-left text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                            {{__('portal.UOM')}}
                        </th>
                        <th scope="col" class="px-2 py-2 border border-black text-left text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                            {{__('portal.Brand')}}
                        </th>

                        <th scope="col" class="px-2 py-2 border border-black text-left text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                            {{__('portal.Remarks')}}
                        </th>

                        <th scope="col" class="px-2 py-2 border border-black text-left text-xs font-medium text-black uppercase tracking-wider" style="background-color: #FCE5CD">
                            {{__('portal.Amount')}}
                        </th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-black border-1 border-black">
                    <tr>
                        <td class="px-2 py-2 whitespace-nowrap text-sm text-black border border-black">
                            1
                        </td>
                        {{--<td class="px-2 py-2 whitespace-nowrap text-sm text-black border border-black">
                            {{ $draftPurchaseOrder->item_code }}
                        </td>--}}
                        <td class="px-2 py-2 whitespace-nowrap text-sm text-black border border-black">
                            {{ $draftPurchaseOrder->quantity }}
                        </td>
                        <td class="px-2 py-2 whitespace-nowrap text-sm text-black border border-black">
                            {{ $draftPurchaseOrder->unit_price }} {{__('portal.SAR')}}
                        </td>
                        <td class="px-2 py-2 whitespace-nowrap text-sm text-black border border-black">
                            {{ $draftPurchaseOrder->uom }}
                        </td>
                        <td class="px-2 py-2 whitespace-nowrap text-sm text-black border border-black">
                            {{ $draftPurchaseOrder->brand }}
                        </td>
                        <td class="px-2 py-2 whitespace-nowrap text-sm text-black border border-black">
                            @if(isset($draftPurchaseOrder->remarks)){{ $draftPurchaseOrder->remarks }} @else {{__('portal.N/A')}} @endif
                        </td>
                        <td class="px-2 py-2 whitespace-nowrap text-sm text-black border border-black">
                            {{ number_format($draftPurchaseOrder->sub_total, 2) }} {{__('portal.SAR')}}
                        </td>
                    </tr>
                    {{--<tr>
                        <td colspan="7" rowspan="4">
                        </td>
                        <td class="px-1 py-1 whitespace-nowrap text-sm text-black border border-black">
                            Sub Total
                        </td>
                        <td class="px-1 py-1 whitespace-nowrap text-sm text-black border border-black">
                            {{ number_format($draftPurchaseOrder->sub_total, 2) }} {{__('portal.SAR')}}
                        </td>
                    </tr>
                    <tr>
                        <td class="px-1 py-1 whitespace-nowrap text-sm text-black border border-black">
                            VAT 15%
                        </td>
                        <td class="px-1 py-1 whitespace-nowrap text-sm text-black border border-black">
                            {{ number_format($draftPurchaseOrder->sub_total * 0.15, 2) }}
                        </td>
                    </tr>
                    <tr>
                        <td class="px-1 py-1 whitespace-nowrap text-sm text-black border border-black">
                            Shipping Fees
                        </td>
                        <td class="px-1 py-1 whitespace-nowrap text-sm text-black border border-black">
                            {{ number_format($draftPurchaseOrder->shipment_cost, 2) }}
                        </td>
                    </tr>
                    <tr>
                        <td class="px-1 py-1 whitespace-nowrap text-sm text-black border border-black">
                            P.O Total
                        </td>
                        <td class="px-1 py-1 whitespace-nowrap text-sm text-black border border-black">
                            {{ number_format($draftPurchaseOrder->sub_total * 0.15 + $draftPurchaseOrder->sub_total + $draftPurchaseOrder->shipment_cost, 2) }}
                        </td>
                    </tr>--}}
                    </tbody>
                </table>

                <div class="flex flex-wrap overflow-hidden bg-white p-4">
                    <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                    </div>
                    <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                    </div>
                    <div class="w-full overflow-hidden lg:w-1/3 xl:w-1/3">
                        <strong>{{__('portal.Sub-total')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ number_format($draftPurchaseOrder->sub_total, 2) }} {{__('portal.SAR')}}<br>
                        <strong>{{__('portal.VAT')}} %: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ number_format($draftPurchaseOrder->sub_total * 0.15, 2) }} {{__('portal.SAR')}}<br>
                        <strong>{{__('portal.Shipment cost')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ number_format($draftPurchaseOrder->shipment_cost, 2) }} {{__('portal.SAR')}}<br>
                        <hr>
                        <strong>{{__('portal.Total')}}: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{ number_format($draftPurchaseOrder->sub_total * 0.15 + $draftPurchaseOrder->sub_total + $draftPurchaseOrder->shipment_cost, 2) }} {{__('portal.SAR')}}<br>
                        <hr>
                    </div>
                </div>

                <div class="flex flex-wrap overflow-hidden  p-4 mt-4">
                    <div class="w-full overflow-hidden lg:w-1/2 xl:w-2/3">
                        <strong>{{__('portal.Mobile Number for OTP')}}: </strong> {{ strip_tags($draftPurchaseOrder->otp_mobile_number) }} <br>
                        <strong>{{__('portal.Delivery Address')}}: </strong> {{ strip_tags($draftPurchaseOrder->delivery_address) }} <br>
                    </div>
                    <div class="w-full overflow-hidden lg:w-1/2 xl:w-1/2">
                        {{--                            <strong>Delivery Information:</strong><br>--}}
                        {{--                            @php $warehouseName =  \App\Models\BusinessWarehouse::where('id', $draftPurchaseOrder->warehouse)->first(); @endphp--}}
                        {{--                            <strong>Warehouse: @if(isset($warehouseName)){{$warehouseName->name}}@endif</strong><br>--}}
                    </div>
                </div>


                {{--                    <div class="flex justify-center">--}}
                {{--                        <div><img src="{{ url('logo-full.png') }}" alt="EMDAD CHAIN LOGO" class="block h-10 w-auto" /></div>--}}
                {{--                    </div>--}}
                <div class="flex justify-between mt-4 mb-4">


                    @if ($draftPurchaseOrder->status == 'approved')
                        <img class="px-3 py-3 h-20" src="{{url('images/stamps/Artboard-9@8x.png')}}" alt="{{__('portal.P.O. APPROVED')}}">
                        {{--                            <span class="px-3 py-3 bg-green-800 text-white rounded">APPROVED P.O</span>--}}
                    @elseif ($draftPurchaseOrder->status == 'cancel')
                        <img class="px-3 py-3 h-20" src="{{url('images/stamps/Artboard-8@8x.png')}}" alt="{{__('portal.P.O. Canceled')}}">
                        {{--                            <span class="px-3 py-3 bg-red-800 text-white rounded">Canceled P.O</span>--}}
                    @elseif ($draftPurchaseOrder->status == 'rejectToEdit')
                        <img class="px-3 py-3 h-20" src="{{url('images/stamps/Artboard-7@8x.png')}}" alt="{{__('portal.Rejected for Edit')}}">
                        {{--                            <span class="px-3 py-3 bg-red-600 text-white rounded uppercase">Rejected for Edit</span>--}}
                    @elseif ($draftPurchaseOrder->status == 'completed')
                    @elseif ($draftPurchaseOrder->status == 'prepareDelivery')
                    @else
                        @if(auth()->user()->registeration_type == 'Buyer')
                            <a href="{{ route('dpo.approved', $draftPurchaseOrder->id) }}" class="inline-flex  mx-4  items-center px-4 py-2 bg-green-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-green-700 active:bg-green-900 focus:outline-none focus:border-green-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">DPO Approved</a>
                        @endif
                        <a href="{{ route('dpo.cancel', $draftPurchaseOrder->id) }}" class="inline-flex  mx-4  items-center px-4 py-2 bg-red-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-700 active:bg-red-900 focus:outline-none focus:border-red-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">Cancel P.O</a>
                        <a href="{{ route('dpo.rejected', $draftPurchaseOrder->id) }}" class="inline-flex  mx-4  items-center px-4 py-2 bg-red-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-700 active:bg-red-900 focus:outline-none focus:border-red-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">Reject to Edit</a>
                    @endif

                </div>

                <div class="flex justify-between px-2 py-2 mt-2 h-15">
                    <div></div>
                    <div class="mt-3">{{__('portal.Thank you for using Emdad platform for your business.')}}</div>
                    {{--                        <div><img src="{{ url('logo-full.png') }}" alt="EMDAD CHAIN LOGO" class="block h-10 w-auto" /></div>--}}
                    <div></div>
                </div>
                <div class="flex justify-end px-2 py-2 h-15">
                    <div class="mt-2">{{__('portal.Copied to Emdad records')}}</div>
                    <div><img src="{{ url('logo-full.png') }}" alt="EMDAD CHAIN LOGO" class="block h-10 w-auto" style="margin-left: auto; margin-right: auto;"/></div>
                </div>

            </div>
        </div>
    </div>
</div>
</body>
</html>
